version: '2.4'
# CPUs and MEM limits set to run under a VM with limited resources (Azure B2s: 2vCPUs, 4GiB RAM)
services:
  # Description: Override settings to services defined in docker-compose.yaml
  caddy:
    cpus: .2
    mem_limit: 400m

  # Description: Serves the frontend of Sourcegraph via HTTP(S).
  sourcegraph-frontend-0:
    cpus: .2
    mem_limit: 400m
 
  # Description: Serves the internal Sourcegraph frontend API.
  sourcegraph-frontend-internal:
    cpus: .2
    mem_limit: 400m
 
  # Description: Stores clones of repositories to perform Git operations.
  gitserver-0:
    cpus: .2
    mem_limit: 400m
 
  # Description: Backend for indexed text search operations.
  zoekt-indexserver-0:
    mem_limit: 400m
  # Description: Backend for indexed text search operations.
  zoekt-webserver-0:
    cpus: .2
    mem_limit: 400m
 
  # Description: Backend for text search operations.
  searcher-0:
    cpus: .2
    mem_limit: 400m
 
  # Description: Rate-limiting proxy for the GitHub API.
  github-proxy:
    cpus: .2
    mem_limit: 400m
 
  # Description: Handles conversion of uploaded precise code intelligence bundles.
  precise-code-intel-worker:
    cpus: .2
    mem_limit: 400m
 
  # Description: Handles repository metadata (not Git data) lookups and updates from external code hosts and other similar services.
  repo-updater:
    cpus: .2
    mem_limit: 400m

  # Description: Manages background processes.
  worker:
    cpus: .2
    mem_limit: 400m

  # Description: Backend for syntax highlighting operations.
  syntect-server:
    container_name: syntect-server
    cpus: .2
    mem_limit: 400m

  # Description: Backend for symbols operations.
  symbols-0:
    cpus: .2
    mem_limit: 400m

  # Description: Prometheus collects metrics and aggregates them into graphs.
  prometheus:
    cpus: .2
    mem_limit: 400m

  # Description: Dashboards and graphs for Prometheus metrics.
  grafana:
    cpus: .2
    mem_limit: 400m

  # Description: Publishes Prometheus metrics about Docker containers.
  cadvisor:
    cpus: .2
    mem_limit: 400m

  # Description: Jaeger all-in-one instance
  jaeger:
    cpus: .2
    mem_limit: 400m

  # Description: PostgreSQL database for various data.
  pgsql:
    cpus: .2
    mem_limit: 400m

  # Description: PostgreSQL database for code intelligence data.
  codeintel-db:
    cpus: .2
    mem_limit: 400m

  # Description: TimescaleDB time-series database for code insights data.
  codeinsights-db:
    cpus: .2
    mem_limit: 400m

  # Description: MinIO for storing LSIF uploads.
  minio:
    cpus: .2
    mem_limit: 400m

  # Description: Redis for storing short-lived caches.
  redis-cache:
    cpus: .2
    mem_limit: 400m

  # Description: Redis for storing semi-persistent data like user sessions.
  redis-store:
    cpus: .2
    mem_limit: 400m
    